# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: appname-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appname-test
  pool: 5
  host: localhost
  username: action
  password:

production:
 <<: *default
 database: <%= ENV['RDS_DB_NAME'] %>
 username: <%= ENV['RDS_USERNAME'] %>
 password: <%= ENV['RDS_PASSWORD'] %>
 host: <%= ENV['RDS_HOSTNAME'] %>
 port: <%= ENV['RDS_PORT'] %>